### ISSUE TITLE
Allow changing batch size during training

### ISSUE THREAD

**Issue by runame** [mlcommons/algorithmic-efficiency#118]
## Description

Some submissions might want to change the training batch size during training. Do we want to support this?

**Comment by znado** [comment]
I think for the tf.data pipelines at least, this would be difficult to do in a way where the numpy arrays returned from the iterator are variable shaped, instead of including padding. In that case, we might as well just give the full batches to the submitter in the `data_selection` method, and let them subsample/accumulate as necessary.

In the current API a submitter can definitely increase the batch size if they want (just call `next(data_iterator)` multiple times), but if they want to take two steps with half the batch size they either have to throw out half the batch each time, or store the unused part of the batch in `optimizer_state`, which isn't very convenient but possible.

Feel free to reopen if this doesn't satisfy what you were thinking of though!
