### ISSUE TITLE
Only import selected workload

### ISSUE THREAD

**Issue by hanlint** [mlcommons/algorithmic-efficiency#19]
Currently, the `submission_runner` takes the `WORKLOADS` dictionary, e.g.:
https://github.com/mlcommons/algorithmic-efficiency/blob/584769427aceeac2835c055fae40f159d4a415d7/submission_runner.py#L30-L33

And attempts to import every module, replacing the dictionary values of `WORKLOADS` with the workload class object:

https://github.com/mlcommons/algorithmic-efficiency/blob/584769427aceeac2835c055fae40f159d4a415d7/submission_runner.py#L292-L297

In case of import failures however, the dictionary values are unchanged, and if we attempt to run that workload, we get a less instructive error:
```
AttributeError: 'dict' object has no attribute 'build_input_queue'
```

Moreover, since most users will be submitting in one framework, the log will be polluted with many import errors for the other frameworks.

Instead, perhaps we only import the workload selected by `FLAGS.workload`, and raise an `ImportError` if fails. 

cc: @znado ?

**Comment by fsschneider** [comment]
Instead of the current flags, we could ask for the framework and the workload separately. For example

```bash
python3 submission_runner.py --framework=jax --workload=mnist --submission_path=...
```

Depending on the `framework` flag we can set `use_jax_rng` and only import the corresponding workloads. At the moment a submitter has to twice state that he uses JAX (once via specifying `mnist_jax` as the workload and once via the `use_jax_rng`).

I think this could result in a clearer interface for the submitters and prevent inconsistencies, i.e. when one submitter uses PyTorch with `use_jax_rng` and another one without `use_jax_rng`.
