### ISSUE TITLE
OGBG OOM'in in eager mode pytorch

### ISSUE THREAD

**Issue by msaroufim** [mlcommons/algorithmic-efficiency#471]
I was looking at making `torch.compile` working with this model but when I commented out all the torch.compile bits from  `submission_runner.py` I got an OOM https://gist.github.com/msaroufim/9c0edebe71ca8f16efec0d29f8399d7c even in eager mode. Not a blocker since i still see the dynamo error on `GraphsTuple` but curious if I'm missing anything or if this was run on a different kind of GPU

**Comment by priyakasimbeg** [comment]
We're running on machines with 8 GPUs and splitting the global_batch_size over the 8 GPUs. So the per_device_batch_size might be too large when spread over 4 GPUs. 
Can you try reduce the batch size by 2x since you are running on 4 GPUs. For the algorithm you ran with, that change can be made here: https://github.com/priyakasimbeg/algorithmic-efficiency/blob/main/reference_algorithms/development_algorithms/ogbg/ogbg_pytorch/submission.py#L14

**Comment by msaroufim** [comment]
Yup that fixed it, thank you! Lemme know if you'd like me to make a PR to divide the batch size by `torch.cuda.device_count()`
